import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/layout/header/header'
import Body from '@/layout/body/body'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Travia Go</title>
        <meta name="description" content="Generated by Travia-go" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Header></Header>
        <Body></Body>
        <div>hi</div>
      </main>
    </>
  )
}
